name = "Tmux"
desc = "Terminal Multiplex"
repo = [ "https://github.com/tmux/tmux.git" ]
branch = "master"

[build]
# https://github.com/tmux/tmux/wiki/Installing#from-source-tarball
# dependencies = [ "SEE OVERRIDES" ]
command = '''
./autogen.sh
./configure
make
'''
artifacts = [ "tmux" ]

[install]
prerequisites = [ "build" ]
dependencies = [ "libevent", "ncurses" ]
command = '''
mkdir -p $SCRY_BINDIR
cp $SCRY_ARTIFACTS/tmux $SCRY_BINDIR/tmux
chmod +x $SCRY_BINDIR/tmux
'''

[update]
prerequisites = [ "uninstall", "build", "install" ]

[uninstall]
command = '''
rm -f $SCRY_BINDIR/tmux
'''

[purge]
command = '''
rm -f ~/.tmux.conf
rm -f ~/.tmux_history
'''