name = "Vim"
desc = "Vi iMproved"
repo = [ "https://github.com/vim/vim.git" ]

[build]
# https://github.com/vim/vim/blob/master/src/INSTALL
dependencies = [ "git", "make", "clang", "libtool-bin" ]
command = '''
make
'''
artifacts = [ "src/vim" ]

[install]
prerequisites = [ "build" ]
command = '''

'''

[update]
prerequisites = [ "build" ]
command = '''
# update steps
'''

[uninstall]
command = '''
# uninstall steps
'''

[purge]
command = '''
# purge steps
'''